### ISSUE TITLE
[ 홍영준 ]

### ISSUE THREAD

**Issue by jjunyjjuny** [codesquad-2021-study/agora#27]
불참 이유는 아직 발표 내용을 작성하지 못 했는데,

1. 백엔드는 처음이라 시리즈로 이어가고 싶은데 지금(새벽) 쓰면 질 낮은 글이 써질거 같아서 주말에 제대로 쓰고 싶다.

2. 최근 평일에 잠을 제대로 잔 적이 없어서 푹 자고 일어나고 싶다. 

입니다.

애매한 회고글이나 질 낮은 글로 참여하기 보다 푹 쉬고 주말에 작성한 내용으로 다음주에 뵙도록 하겠습니다..

**Comment by kowoohyuk** [comment]
ㅠㅠㅠ 정말 수고 많으셨습니다..  
저도 글을 결국 쓰지 못했는데 저는 다음에도 평범한 글로 찾아뵐거 같네요!  

쭉 쉬고 작성한 내용.. 기대하겠습니다 ::)

주말은 편히 쉬십쇼!
