### ISSUE TITLE
[김양원]

### ISSUE THREAD

**Issue by adelakim5** [codesquad-2021-study/agora#29]
최근 이사 문제로 정신이 없었습니다. 그래서 제대로 준비된게 없네요 ㅜㅜ 
다음주에 준비된 모습으로 뵙겠습니다 ..

**Comment by kowoohyuk** [comment]
이사 가기 전에 집 구경하는 게 제일 재미있는 거 같아요!

가을 입사를 미리 축하드리며, 이사 화이팅임다 :)
